root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "./main.exe"
  full_bin = "./tmp/main.exe"
  args_bin = []
  entrypoint = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  exclude_dir = ["tmp", "vendor", "testdata", "uploads", ".git"]

  exclude_file = []
  exclude_regex = ["_test\\.go$"]

  delay = 1000
  exclude_unchanged = false
  follow_symlink = false
  ignore_dangerous_root_dir = false
  kill_delay = "500ms"
  poll = false
  poll_interval = 0
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true
  clean_tmp_dir_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true