host: localhost:8123
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Документация запросов микросервиса Auth
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OldMine Auth Api
  version: "1.0"
paths: {}
swagger: "2.0"
